### ISSUE TITLE
你好，用了您的这个库，发现图片是整体放大的，设置拉伸的区域没有用

### ISSUE THREAD

**Issue by tiansuo** [humanheima/NinePatchDrawableLib#1]
demo也试了，图片整体放大，设置的垂直和水平拉伸区域没有作用，求解

**Comment by YuewenDumingwei** [comment]
从资源文件夹加载的话，设计导出的是几倍图要放在对应的文件夹中。如果高倍图放在低倍文件夹中肯定会导致图片放大。3倍图要放到drawable-xxhdpi，2倍图放到drawable-xhdpi。如果发现图片缩放不对，可以先把图片移动到不同的 drawable 文件夹试试。

**Comment by humanheima** [comment]
从资源文件夹加载的话，设计导出的是几倍图要放在对应的文件夹中。如果高倍图放在低倍文件夹中肯定会导致图片放大。3倍图要放到drawable-xxhdpi，2倍图放到drawable-xhdpi。如果发现图片缩放不对，可以先把图片移动到不同的 drawable 文件夹试试。

**Comment by tiansuo** [comment]
感谢大佬，解决了，不错，还是我😂



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月29日 16:39 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [humanheima/NinePatchDrawableLib] 你好，用了您的这个库，发现图片是整体放大的，设置拉伸的区域没有用 (Issue #1) |

从资源文件夹加载的话，设计导出的是几倍图要放在对应的文件夹中。如果高倍图放在低倍文件夹中肯定会导致图片放大。3倍图要放到drawable-xxhdpi，2倍图放到drawable-xhdpi。如果发现图片缩放不对，可以先把图片移动到不同的 drawable 文件夹试试。
